### ISSUE TITLE
Line Formatting Bug

### ISSUE THREAD

**Issue by TheAugustinerGuy** [DSD-DBS/capella-dockerimages#21]
Hi,

I recently noticed that there exists a simple line formatting error in teams for capella web instance. For example in the picture below there is an arrow which has added by line formatting i.e. using right click -> format -> arrow type. 
![image](https://user-images.githubusercontent.com/105649953/168599469-eff7103c-5da0-48c5-90e1-2120d0e093fd.png)
The issue here is that, the arrow or any other formatting with regards to line thickness or line type done on the line vanishes on session restart i.e. Starting a session post termination.

**Comment by MoritzWeber0** [comment]
Hi @TheAugustinerGuy, thanks for reporting the bug. The issue is not directly related to the Capella Docker images. Instead, it's a general issue with Capella. The behaviour that the issue vanishes on session restart applies to every restart of Capella, so I'd like to ask you to report the issue here: https://github.com/eclipse/capella/issues. This allows the Capella team to take care of the problem themselves.
